# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5830783c216762cb75bb6248d79f8ab19a5149df163c73e61d2ad512e18ba93a3642bf7f689fe3ca317a157402bafcffa85a23926e3abc6305c5bfcd600de540

test:
  secret_key_base: f434aaf0986c2b3a3a741723d2b56cb850e4e27b4853e9ae6bfa76175740982285bf0132cbb88f8943df5633da73554c8002bfd6eec62bf4ecfbb8298a1206a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
